# Autogenerated wrapper script for FastHadamardStructuredTransforms_jll for x86_64-w64-mingw32
export libfasttransforms

JLLWrappers.@generate_wrapper_header("FastHadamardStructuredTransforms")
JLLWrappers.@declare_library_product(libfasttransforms, "libfasttransforms.dll")
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_library_product(
        libfasttransforms,
        "bin\\libfasttransforms.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
